name: Azure kv sync 

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' 

jobs:
  kv-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Azure authentication
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        
      run: echo "Azure authentication environment variables set."

    - name: Azure KeyVault Secrets Migration
      uses: /devwithkrishna/azure-keyvault-secrets-sync-action@main
      with:
        source_keyvault: 'ARCHITECTS-KEYVAULT'
        destination_keyvault_names: 'TEST1XEWR,MyxqwVult'
        secret_names: 'test,test1,JENKINS-USER-LOGIN,SLACK-EMAIL-ID'
        target_secret_names: 'target1,target2,target3,target4' # optional
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
