name: python-variable-test
run-name: Triggered by ${{ github.actor }} on ${{ github.event_name }} event
on: [push, pull_request]
jobs:
  python-version-test:
    runs-on: ubuntu-latest
    steps:
      - name: setup python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.2'
      - name: py version
        run: |
          python_version=$(python3 --version) >> "$GITHUB_ENV"
      - name: Use the value
        id: step_two
        run: |
          printf '%s\n' "$python_version" # This will output python_version
      # - name: check-python-version
        # run: python --version
      - name: Check completed
        run: echo "Arigato ${{ github.actor }} & python version is ${python_version} . Job is completed now"
